# Generated by Django 3.0.5 on 2020-06-19 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchinfo',
            name='gameData',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='matchinfo',
            name='gameId',
            field=models.CharField(max_length=100),
        ),
    ]
